telegram_token: "6196461025:AAFwd3bPlSH0-ncV_WrYEhqEVsnuT573LWE"
bot_id: "eugenia_bot_1" # each bot needs to have a unique bot id for short term memory backup purpose 
openai_api_key: "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"
stripe_token: "350862534:LIVE:NzgwNjJmY2Y2NjFm"
stripe_token_test: "284685063:TEST:ZjZjMDNkMGE0NmY0" # for Test
use_chatgpt_api: true
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as integers

#available token for new users before they create an account
available_output_token_new_user: 300

return_n_generated_images: 1
n_chat_modes_per_page: 5
enable_message_streaming: false  # if set, messages will be shown to user word-by-word

# MongoDB
mongodb_uri_remote: "mongodb+srv://me:NtWp6cbeuKEmta02@starai.bnv7c.mongodb.net/?retryWrites=true&w=majority"
short_term_memory_backup_key: "EugeniaTelegramBot1ShortTermMemoryLog"


# voice clone
#playht
playht_user_id: "lUTFPtLCfiP68Bbw0EV4dVJQD5n2"
playht_api_key: "a65d351aba794e7fb4d6f17162311025"

#pinecone
pinecone_index_name: "eugenia"

#celebrity namespace
celebrity_namespace: "eugeniacooney_telegram_bot"

#nodejs server
node_server_password: "fhawjthaj-hthjerahr234oru0ufhgarp324ytp98ayfpsdayfuh4wiu"
node_server_url: "https://pinecone-client-7719a66a0ebc.herokuapp.com" 

#policy docs
policy: "https://docs.google.com/document/d/156UateEvQ2ZPAbG1qeZR-29WYgzYO3edfoDV3O4PgFQ/edit?usp=sharing"